### ISSUE TITLE
move docs?

### ISSUE THREAD

**Issue by mnyrop** [NYULibraries/spatial_data_repository#102]
After we refactor deployment (e.g., use [Capistrano](https://capistranorb.com/documentation/overview/what-is-capistrano/) instead of checking out git tags directly), can/should we consolidate the [the standalone sdr-documentation repo](https://github.com/NYULibraries/sdr-documentation) into the [/docs](https://github.com/NYULibraries/spatial_data_repository/tree/master/docs) directory of this repo? This would have the added benefit of versioning docs alongside source code. However, it doesn't make sense until we switch our deployments, since we'd rely on Cap to skip over `/docs` on deploy.

**Comment by andrewbattista** [comment]
I think this is a good idea and is something I can start working on. However, I think there's a question of which documentation. There's a lot of scripts and workflow / processing documents in the sdr-documentation repo that maybe better belong there, or in SdrFriend? Making a note to talk about it soon...
