### ISSUE TITLE
Restricted IndexMaps do not display

### ISSUE THREAD

**Issue by ewlarson** [NYULibraries/spatial_data_repository#26]
NYU restricted proxy code hard codes a WMS data-url endpoint when the record is restricted. Need to allow geojson IndexMap value to be passed through as well.

settings.yml writes the WMS endpoint into the logic here:
RESTRICTED_URL: 'https://maps-restricted.geo.nyu.edu/geoserver/wms'

The models/concerns/wms_rewrite_concern.rb also plays a part here.

**Comment by nmwolf** [comment]
Closed as superceded by current non-proxy approach to restricted records in latest GBL.
