### ISSUE TITLE
A11y regression tests

### ISSUE THREAD

**Issue by mnyrop** [NYULibraries/spatial_data_repository#282]
Should run within/alongside rspec feature tests

Of note: https://github.com/dequelabs/axe-core-gems/blob/develop/packages/axe-core-rspec/README.md

Can start with: homepage, results page, item page `expect(page).to be_axe_clean` ...?

**Comment by the-codetrane** [comment]
https://github.com/NYULibraries/spatial_data_repository/pull/279/commits/7d43fcb1c0485fd99345240964c7857fb32f04ea
