### ISSUE TITLE
Staging UI: Displaying Versions

### ISSUE THREAD

**Issue by mnyrop** [NYULibraries/spatial_data_repository#286]
On staging home page:
- [x] a [geoblacklight verison](https://geo-stage.library.nyu.edu/#geoblacklight-version) tag appeared ("GeoBlacklight version 4.1.0"). It should be removed or moved to the footer below the SDR version tag
- [x] the [SDR version](https://geo-stage.library.nyu.edu/#footer-links) in the footer needs to be fixed; it's no longer displaying the version next to "Running SDR"

**Comment by the-codetrane** [comment]
https://github.com/NYULibraries/spatial_data_repository/pull/279/commits/8b83578ac3a8cd38a86c6178ab5612fb12d1eafd
