### ISSUE TITLE
Staging UI: Leaflet View

### ISSUE THREAD

**Issue by mnyrop** [NYULibraries/spatial_data_repository#288]
Leaflet is no longer bounding default view to relevant area, see [staging](https://geo-stage.library.nyu.edu/catalog/nyu-2451-36739) vs [prod](https://geo.nyu.edu/catalog/nyu-2451-36739) example.

**Comment by the-codetrane** [comment]
https://github.com/NYULibraries/spatial_data_repository/pull/279/commits/edc4fbbf94c8c47186ba29bf39e5006966abe02c
