### ISSUE TITLE
Staging UI: IIIF Service gap

### ISSUE THREAD

**Issue by mnyrop** [NYULibraries/spatial_data_repository#289]
Staging has [IIIF records](https://geo-stage.library.nyu.edu/?search_field=all_fields&q=IIIF)  pulled in from other institutions but none of them work. We'll need to implement a IIIF viewer (either with Leaflet, Mirador, etc.) or prune out those records.

**Comment by the-codetrane** [comment]
https://github.com/NYULibraries/spatial_data_repository/pull/279/commits/591ffe897239442a3da0c2b30bae2f8cf53a613d
