### ISSUE TITLE
Remove "Recently Updated" section from Homepage

### ISSUE THREAD

**Issue by mnyrop** [NYULibraries/spatial_data_repository#294]
- [x] Remove section
- [x] Display 4 "Featured Collections" at full width instead

See: https://github.com/NYULibraries/spatial_data_repository/blob/d8e65b867be91978d502210b4791a9f747ccab7b/lib/nyugeoblacklight/curated_collections.rb#L12
<img width="600" alt="Screenshot 2023-12-08 at 2 50 45 PM" src="https://github.com/NYULibraries/spatial_data_repository/assets/25022284/3b267134-90a9-4ad0-ae26-7cf55615c9d7">

**Comment by the-codetrane** [comment]
https://github.com/NYULibraries/spatial_data_repository/pull/296https://github.com/NYULibraries/spatial_data_repository/pull/296



![Image](https://github.com/NYULibraries/spatial_data_repository/assets/12383156/d4e3af17-d990-4278-915c-9d75960b6d1b)
