### ISSUE TITLE
Suppress kmz download option in application

### ISSUE THREAD

**Issue by mnyrop** [NYULibraries/spatial_data_repository#295]
Should follow up to see if the download endpoint is configured in the records—we don't want other institutions to using our broken routes.

**Comment by the-codetrane** [comment]
https://github.com/NYULibraries/spatial_data_repository/pull/297



![Image](https://github.com/NYULibraries/spatial_data_repository/assets/12383156/194d9f7c-78e0-4dd7-a36c-062540199c65)
