### ISSUE TITLE
A popup success/error message will display as bleedthrough HTML if user navigates to a new page

### ISSUE THREAD

**Issue by nmwolf** [NYULibraries/spatial_data_repository#313]
This happens when a user does something to prompt a success or error message, then leaves the message up (does not X it out), and navigates to a new page

On the loading of the next page, the error turns into HTML.

Here's an example where a "Ready to download GeoJSON" success message turns into HTML when navigating to a new page:

![Image](https://github.com/NYULibraries/spatial_data_repository/assets/11075283/383ddad7-61cd-4896-8454-48dc60f6e69c)

**Comment by spilth** [comment]
Steps to replicate this issue:

- Navigate to https://geo.nyu.edu/catalog/nyu-2451-34625
- Click the **Download** disclosure button in the right sidebar
- Click on **GeoJSON**
- Wait for Bootstrap Info Alert to display
- Click **Back to search**

**Expected:** Info Alert disappears

**Actual:** Info Alert persists and contents change to its HTML source

If you refresh the page, the alert disappears

**Comment by spilth** [comment]
I am able to replicate this issue with a vanilla install of GeoBlacklight, so I suspect it's not specific to the NYU repository.

I am going to open an issue in the GeoBlacklight repository, mention it on their Slack and see if anybody else is experiencing this issue.

![Image](https://github.com/user-attachments/assets/e9d89651-4718-4cf2-b771-2701cb3302f2)

**Comment by spilth** [comment]
Opened an issue about this in the GeoBlacklight repository: https://github.com/geoblacklight/geoblacklight/issues/1397

**Comment by spilth** [comment]
@nmwolf This has been fixed in core and will likely be in a future release: https://github.com/geoblacklight/geoblacklight/pull/1398

**Comment by spilth** [comment]
Addressed by #371
