### ISSUE TITLE
Vector records not showing individual record feature preview when clicking on feature

### ISSUE THREAD

**Issue by nmwolf** [NYULibraries/spatial_data_repository#314]
Some or all vector type records are not displaying the preview single-record feature in the record page that presents the underlying tabular record for that feature. The problem seems to be the same for point, line, and polygon layers.

Examples include:

POINT
Record: https://geo.nyu.edu/catalog/nyu-2451-44260

![Image](https://github.com/NYULibraries/spatial_data_repository/assets/11075283/87d4cedd-6003-4e5a-b1a3-98cdf56fe4ff)

Also: https://geo.nyu.edu/catalog/nyu-2451-44256

LINE
Record: https://geo.nyu.edu/catalog/nyu-2451-36787

POLYGON
Record: https://geo.nyu.edu/catalog/nyu-2451-43803

**Comment by spilth** [comment]
I've replicated the requests that the frontend is making directly to the GeoServer and requests for all 3 maps generate the following error:

```
<?xml version="1.0" encoding="UTF-8"?>
<ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ogc https://maps-public.geo.nyu.edu:443/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd">
    <ServiceException>
      Internal error occurred
java.io.IOException: Error occured calculating bounds for nyu_2451_43803
Error occured calculating bounds for nyu_2451_43803
ERROR: function st_force_2d(geometry) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 18
</ServiceException>
</ServiceExceptionReport>
```

This StackOverflow post suggests it may be because of an old version of GeoTools packaged with GeoServer: https://gis.stackexchange.com/questions/353638/error-when-publishing-a-table-layer-from-postgis-to-geoserver

![Image](https://github.com/user-attachments/assets/7dc4dd16-1938-4f83-baf8-3fd6fe84b96e)

**Comment by gulshan11** [comment]
Logging the coordinates of three data outliers with ID's that do not fall under expected region.
<img width="612" alt="image" src="https://github.com/user-attachments/assets/27aabb1a-9bfb-479d-8aee-2d03bcf32018">

**Comment by nmwolf** [comment]
Issue caused by missing Geoserver layers, will be fixed via current audit.
