### ISSUE TITLE
EPSG Shapefile failure to download

### ISSUE THREAD

**Issue by nmwolf** [NYULibraries/spatial_data_repository#322]
Discovered issue with this record, likely widespread, ESPG version of file won't download (throws popup error):

https://geo.nyu.edu/catalog/nyu-2451-36334

No idea what cause could be (Geoserver?)

**Comment by spilth** [comment]
Testing this on staging I see the following error in the Rails app logs:

```
Geoblacklight::Exceptions::WrongDownloadFormat expected application/zip received application/xml
Wrong download type
```

**Comment by spilth** [comment]
I don't know if it's a permission issue but I'm not able to find this layer on the Restricted GeoServer.

I've also noticed that the GBL server says there are 2,130 Public and 1,993 Restricted results from the Institution NYU. Yet the GeoServers report 2,123 Public and 1,765 Restricted results. Makes me wonder if the Solr index is out of date and we're listing things that are no long in GeoServer.

**Comment by nmwolf** [comment]
Interesting @spilth or @gulshan11 any chance you can generate a list of sdr IDs (e.g. nyu-2451-36737) for all assets in Geoserver, with or without restricted/unrestricted information? We can do a diff against the IDs listed in the canonical metadata store https://github.com/opengeometadata/edu.nyu

**Comment by spilth** [comment]
I should be able to generate the list of IDs

**Comment by spilth** [comment]
I posted the diff in Slack

**Comment by spilth** [comment]
FWIW, the layer mentioned in this bug (2451-36334) is one of the entries that shows up in the Aardvark Meta Data but does not have a WMS or WMS entry.

**Comment by spilth** [comment]
I have delivered (via Slack) a CSV showing which `edu.nyu` Aardvark entries are missing from the WFS and WMS services in their respective GeoServer instances. I believe the issue from here on out is a metadata-related one.
