### ISSUE TITLE
Dev Environment: Search Autocomplete is not working

### ISSUE THREAD

**Issue by spilth** [NYULibraries/spatial_data_repository#356]
While investigating an extraneous `suggest` route I determined that GBL comes with a Search Autocomplete feature that doesn't seem to be working for SDR.

I also suspect the `suggest` route is a pre-GBL 4 route for this.

**Comment by spilth** [comment]
This seems to only be happening in local development. I tried on two different Macs and they both have this issue.

Solr Logging shows the following:

```
SuggestComponent
Exception in building suggester index for mySuggester:
java.security.AccessControlException: access denied ("java.io.FilePermission" "/private/var/folders/dc/2ml72_bd2ms51kwbbch9bwkr0000gp/T/suggester_input_3.tmp" "write")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
```

**Comment by spilth** [comment]
This appears to be either a Solr 9.2+ issue or a solr_wrapper issue. Waiting to see if this is sorted out in the GeoBlacklight Slack.

**Comment by nmwolf** [comment]
Closed since this feature is working in production, likely not needed as a feature to work with dev instance.
