### ISSUE TITLE
Update Restricted Records Warning

### ISSUE THREAD

**Issue by spilth** [NYULibraries/spatial_data_repository#373]
For a restricted NYU record such as https://geo.nyu.edu/catalog/nyu-2451-34625

We want to update the alert from:

This dataset is only available to members of the New York University community and is limited to current students, staff, and faculty. Do not copy or redistribute this data. If you have questions about what constitutes fair use of this material, please contact us directly at [data.services@nyu.edu](mailto:data.services@nyu.edu).

To: 

This dataset is only available to members of the <b>New York University</b> community and is limited to <em>current</em> students, staff, and faculty. Do not copy or redistribute this data. If you have questions about what constitutes fair use of this material, please contact us directly at <a href='mailto:[data.services@nyu.edu](mailto:data.services@nyu.edu)'>[data.services@nyu.edu](mailto:data.services@nyu.edu)</a>.

Please note that access while on the NYU wifi network or via <a href="https://www.nyu.edu/life/information-technology/infrastructure/network-services/vpn.html">NYU VPN</a> is required to preview the data below; authenticated users may use the asset download features without NYU VPN.

**Comment by nmwolf** [comment]
Completed and pushed to production.
