### ISSUE TITLE
Implement Blacklight's versioning display logic

### ISSUE THREAD

**Issue by mnyrop** [NYULibraries/spatial_data_repository#39]
Currently, SDR tagged release versions loosely map onto the GBL version they use. Is this a useful practice, or can/should these be decoupled? If so, how should we define our own versioning scheme, i.e., what do we count as a 'breaking API change' ? Worth revisiting + documenting

**Comment by andrewbattista** [comment]
Given that we only recently started tagging releases at all, I am totally on board with whatever structure makes the most sense for us. I'll add this to the board for now, but I'm open to any schema that makes sense for us. My vote would be to use the ```MAJOR.MINOR.PATCH``` convention, where the MAJOR and MINOR refer to the essential master branch version of the core GeoBlacklight project that we are on. 

But yes, totally worth documenting and taking into consideration larger practices

**Comment by mnyrop** [comment]
That makes sense. Maybe we can work on adding a little blurb like in https://github.com/projectblacklight/blacklight_oai_provider#versioning. Its a BL plugin rather than a BL implementation, but it's still useful I think.

**Comment by andrewbattista** [comment]
Just saw this today on how Blacklight implements this to make the version number prominent. We might want to consider adding as well? https://github.com/projectblacklight/demo.projectblacklight.org/blob/master/app/views/catalog/_home_text.html.erb#L32

**Comment by andrewbattista** [comment]
Given our discussion, let's try to implement this in our local version to keep track of the actual version that is being used. We will also need to update the Contributing guidelines to remind people to update the version.
