### ISSUE TITLE
Problems with Relations / Related records logic

### ISSUE THREAD

**Issue by andrewbattista** [NYULibraries/spatial_data_repository#48]
I'm almost certain this is a metadata issue, but for some records, clicking the related data link leads to an "item not found" screen

**Comment by andrewbattista** [comment]
Upon further review, I think this is something hard-coded into the related record behavior in the application. I think GeoBlacklight constructs a search string incorrectly upon click. See screenshots:

![record-relations-1](https://user-images.githubusercontent.com/9846551/77654333-535a2800-6f47-11ea-8e76-2adea76acddf.png)
and
![Source Dataset  nyu_-2451_-60460 - NYU Spatial Data Repository Search Results](https://user-images.githubusercontent.com/9846551/77654503-87354d80-6f47-11ea-9495-fc2f16909e5c.png)

The url path for the search string is `/catalog?f%5Bdct_source_sm%5D%5B%5D=nyu%5C-2451%5C-60460` but should be `/catalog?f%5Bdct_source_sm%5D%5B%5D=nyu-2451-60460`

I believe this behavior is described [here](https://github.com/geoblacklight/geoblacklight/wiki/Using-data-relations-widget)

I think what's happening has to do with our slug convention changing from `nyu_2451_xxxxx` to `nyu-2451-xxxxx`

**Comment by nmwolf** [comment]
Closed as fixed in upgrade to most recent GBL.
