### ISSUE TITLE
Finish ingest of latest ML InfoMap metadata

### ISSUE THREAD

**Issue by andrewbattista** [NYULibraries/spatial_data_repository#56]
The metadata for the latest purchase of ML InfoMap is basically done but needs a bit of work:

- Fix encoding issues 

- Force shapefiles into utf-8 so that they can be converted to PostGIS and connected to GeoServer

- Test records in vagrant box and then publish

**Comment by kwissel** [comment]
Cleaned up special symbols in metadata.  Should be ready for ingest.  However, I am not ready to ingest it!  Link: https://docs.google.com/spreadsheets/d/1xM7fJYzm_hb33xHc-tFOAKPnSB_HC9dtAi0P8rVGzQw/edit?usp=sharing

**Comment by andrewbattista** [comment]
Great! I will transform this into JSON documents, but we still need to deal with the GeoServer piece. We can do this together if we carve out a half hour or os

**Comment by andrewbattista** [comment]
records are live... now just need to deal with GeoServer

**Comment by kwissel** [comment]
Have dowloaded 103 files.  Not sure where to put them - git noted too many.  But they are ready to unzip and run a de-spacing script.

**Comment by nmwolf** [comment]
To complete using current SDR ingest workflow.
