### ISSUE TITLE
Create backup copy and management workflow for "in house" metadata

### ISSUE THREAD

**Issue by andrewbattista** [NYULibraries/spatial_data_repository#58]
We currently have a smattering of secret "in house" metadata that we have cleaned from OpenGeoMetadata but have cleaned or otherwise customized for our own purposes. Currently this sits directly on our production server and in our Solr index, but nowhere else. We should have backup, documentation, and a management workflow (or something like it) in place

**Comment by kwissel** [comment]
Is this something I can help with?

**Comment by andrewbattista** [comment]
@kwissel yes! I created such a repo at https://github.com/NYU-DataServices/gis-metadata - we have several others to add and will hopefully have more at the end of the sprint.

**Comment by kwissel** [comment]
To be added Harvard, Columbia and Berkeley.

**Comment by andrewbattista** [comment]
This is done! Added all of our local collections, including the @nmwolf records from Princeton,  to https://github.com/NYU-DataServices/gis-metadata
