### ISSUE TITLE
Finish Metadata Creation and ingest of Baruch records

### ISSUE THREAD

**Issue by andrewbattista** [NYULibraries/spatial_data_repository#76]
We have some new files from CUNY Baruch submitted that need to be added to the SDR. The handles and metadata are already created; files just need to be pushed through to Geoserver

**Comment by andrewbattista** [comment]
I added and updated the real estate records, but I still need to finish the rest of the Baruch refresh. More to come!

**Comment by nmwolf** [comment]
Will be completed through ongoing audit of any unfinished records in SDR and pushing them to completion.
