### ISSUE TITLE
Finally add repaired Princeton Records to production

### ISSUE THREAD

**Issue by andrewbattista** [NYULibraries/spatial_data_repository#77]
We have some Princeton Records with bad encoding and that don't reference the right IIIF endpoints. @andrewbattista has these mostly repaired but we need to force them into UTF-8 delete the existing records, then add new ones to our production instance

**Comment by andrewbattista** [comment]
add documentation on how and why to avoid this. I will need help on the diacritics

**Comment by nmwolf** [comment]
Patched NYU records are zipped up at https://drive.google.com/file/d/1fOhLA_GRjnETGoW4HnI47roICakpLoIk/view?usp=sharing
Summary of 2 QC issues (list of NYU records no longer in Princeton github repo; list of some records with differing layer_ids available at https://drive.google.com/file/d/1fNJuf_jtHjLpQaWsWUpcoXe0YHu5uLFJ/view?usp=sharing

**Comment by andrewbattista** [comment]
Thanks for doing this! Unfortunately I checked them and none of them are valid. At a first glance, I think it's because the ```solr_year_i``` field needs to have a precision of 0 (1915 instead of 1915.0). Is this an easy fix? I can also make it an issue over in our newly created repository?
